version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: lifeplan_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lifeplan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - remix_network
    restart: always

volumes:
  postgres_data:

networks:
  remix_network:
    driver: bridge
